
name: Summary titles
on: [push, pull_request,workflow_dispatch]
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          summary-title: 'Headless'
          config-file: 'cypress.config.ts'
