name: Cypress Tests

on: [push, pull_request,workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name:
        run: ls
